### ISSUE TITLE
Help!!  Look this What happened!

### ISSUE THREAD

**Issue by Kuiperabxy** [phingofficial/phing#1607] opened 2021-05-30 06:57 UTC
![Snipaste_2021-05-30_14-55-13](https://user-images.githubusercontent.com/47216449/120095176-17c47a80-c157-11eb-8d00-00dbb67052aa.png)

**Comment by siad007** [comment] 2021-05-30 09:36
Duplicate of https://github.com/phingofficial/phing/issues/1399
Fixed in https://github.com/phingofficial/phing/pull/1413
Please update your phing installation to 3.x

**Closed by siad007** 2021-05-30 09:36 UTC
Labels: wontfix
