### ISSUE TITLE
PHPUnitReportTask fails with XSLTProcessor::importStylesheet() unable to read phar:/usr/local/bin/phing/etc/str.replace.function.xsl (Trac #1240)

### ISSUE THREAD

**Issue by phing-issues-importer** [phingofficial/phing#584] opened 2016-10-09 11:19 UTC
Hi,

my build fails with:

XSLTProcessor::importStylesheet(): I/O warning : failed to load external entity "phar:/usr/local/bin/phing/etc/str.replace.function.xsl", file: phar:///usr/local/bin/phing/classes/phing/tasks/ext/phpunit/PHPUnitReportTask.php

See buildfile below: It successfully executed the tests and creates a valid logfile.xml as expected. Converting test results with <<phpunitreport> then fails.

Using both Phing and PHPUnit PHAR archives.

After extracing the Phing PHAR, I see that is DOES contain phar:/usr/local/bin/phing/etc/str.replace.function.xsl.

Environment:
Phing 2.13.0
PHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10)
libxslt Version 1.1.28 with XSL enabled
Registered PHP Streams: https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip
PHPUnit 4.8.7 by Sebastian Bergmann and contributors.
Linux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) https://www.phing.info/trac/ticket/1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)

Buildfile (paths changed, please adjust as needed):

```
<?xml version="1.0"?>

<project name="MyProject" basedir="." default="tests_with_report">
  <target name="prepare">
    <mkdir dir="testreport"/>
  </target>

  <target name="clean">
    <delete dir="testreport"/>
  </target>

  <target name="tests_with_report" depends="prepare">
    <phpunit bootstrap="bootstrap.php" pharlocation="/usr/local/bin/phpunit">
      <batchtest>
        <fileset dir="tests">
          <include name="config/*Test.php"/>
        </fileset>
      </batchtest>

      <formatter type="xml" todir="testreport" outfile="logfile.xml" />
    </phpunit>

        <phpunitreport infile="logfile.xml"
                   format="frames"
                   todir="testreport"/>


  </target>
</project>
```

---

<phpunitreport> is successfully executing and creating html base report on a different system with PHP 5.4.45-0+deb7u2.

Migrated from https://www.phing.info/trac/ticket/1240

``` json
{
    "status": "new", 
    "changetime": "2016-09-29T08:11:42", 
    "description": "Hi,\n\nmy build fails with:\n\nXSLTProcessor::importStylesheet(): I/O warning : failed to load external entity \"phar:/usr/local/bin/phing/etc/str.replace.function.xsl\", file: phar:///usr/local/bin/phing/classes/phing/tasks/ext/phpunit/PHPUnitReportTask.php\n\nSee buildfile below: It successfully executed the tests and creates a valid logfile.xml as expected. Converting test results with <<phpunitreport> then fails.\n\nUsing both Phing and PHPUnit PHAR archives.\n\nAfter extracing the Phing PHAR, I see that is DOES contain phar:/usr/local/bin/phing/etc/str.replace.function.xsl.\n\nEnvironment:\nPhing 2.13.0\nPHP 5.6.14-0+deb8u1 (cli) (built: Oct  4 2015 16:13:10)\nlibxslt Version 1.1.28 with XSL enabled\nRegistered PHP Streams: https, ftps, compress.zlib, compress.bzip2, php, file, glob, data, http, ftp, phar, zip\nPHPUnit 4.8.7 by Sebastian Bergmann and contributors.\nLinux version 3.16.0-4-amd64 (debian-kernel@lists.debian.org) (gcc version 4.8.4 (Debian 4.8.4-1) ) #1 SMP Debian 3.16.7-ckt11-1+deb8u3 (2015-08-04)\n\nBuildfile (paths changed, please adjust as needed):\n\n<?xml version=\"1.0\"?>\n\n<project name=\"MyProject\" basedir=\".\" default=\"tests_with_report\">\n  <target name=\"prepare\">\n    <mkdir dir=\"testreport\"/>\n  </target>\n\n  <target name=\"clean\">\n    <delete dir=\"testreport\"/>\n  </target>\n\n  <target name=\"tests_with_report\" depends=\"prepare\">\n    <phpunit bootstrap=\"bootstrap.php\" pharlocation=\"/usr/local/bin/phpunit\">\n      <batchtest>\n        <fileset dir=\"tests\">\n          <include name=\"config/*Test.php\"/>\n        </fileset>\n      </batchtest>\n\n      <formatter type=\"xml\" todir=\"testreport\" outfile=\"logfile.xml\" />\n    </phpunit>\n\n        <phpunitreport infile=\"logfile.xml\"\n                   format=\"frames\"\n                   todir=\"testreport\"/>\n\n\n  </target>\n</project>\n\n-----\n\n<phpunitreport> is successfully executing and creating html base report on a different system with PHP 5.4.45-0+deb7u2.", 
    "reporter": "Ulrich", 
    "cc": "", 
    "resolution": "", 
    "_ts": "1475136702149451", 
    "component": "phing-tasks-phpunit", 
    "summary": "PHPUnitReportTask fails with XSLTProcessor::importStylesheet() unable to read phar:/usr/local/bin/phing/etc/str.replace.function.xsl", 
    "priority": "minor", 
    "keywords": "phar XSLTProcessor PHPUnit phpunitreport I/O warning", 
    "version": "2.13.0", 
    "time": "2016-01-15T11:45:41", 
    "milestone": "2.16.0", 
    "owner": "", 
    "type": "defect"
}
```

**Comment by phing-issues-importer** [comment] 2016-10-09 11:33
Trac update at 20160929T08:11:42: 
* mrook changed milestone from "Backlog" to "2.16.0"
* mrook changed priority from "tbd" to "minor"

**Comment by mrook** [comment] 2016-11-02 21:44
This is caused by the ```xsl:include``` statements in both phpunit .xsl files, which do not support / understand phar paths.

**Comment by siad007** [comment] 2016-11-16 20:29
@mrook what do you think about something like that inside PHPUnitReportTask:
```php
protected function getStyleSheet()
    {
        $xslname = "phpunit-" . $this->format . ".xsl";

        if ($this->styleDir) {
            $file = new PhingFile($this->styleDir, $xslname);
        } else {
            $path = Phing::getResourcePath("phing/etc/$xslname");

            if ($path === null) {
                $path = Phing::getResourcePath("etc/$xslname");

                if ($path === null) {
                    throw new BuildException("Could not find $xslname in resource path");
                }
            }
/////////////// START ///////////////////////////////////////////////////////////////////////////////////////
            $file = new PhingFile($path);
            $tmpDir = PhingFile::getTempDir() . '/phing/';
            $destFile = new PhingFile($tmpDir, 'phpunit-stylesheet.xsl');
            if (!$file->copyTo($destFile)) {
                throw new BuildException("Could not copy $xslname to $tmpDir");
            }
            $file = $destFile;
/////////////// END ////////////////////////////////////////////////////////////////////////////////////////
        }

        if (!$file->exists()) {
            throw new BuildException("Could not find file " . $file->getPath());
        }

        return $file;
    }
```

**Comment by mrook** [comment] 2016-12-06 09:07
@siad007 I don't think that'll fix the issue. The problem is the ```xsl:include``` statement in ```phpunit-frames.xsl``` and ```phpunit-noframes.xsl```. We need to either wrap that in a PHP function (http://php.net/manual/de/xsltprocessor.registerphpfunctions.php) or figure out another way.

**Comment by siad007** [comment] 2016-12-07 16:50
@mrook I thought that the main problem is that the stylesheets are inside the phar? Moving to file based tmp dir should solve this. Or what did i overlooked?

**Comment by mrook** [comment] 2016-12-20 13:48
You are right about the phar, but it's actually including the ```str.replace.function.xsl``` file that's the main problem.

**Closed** 2017-01-18 19:45 UTC
Labels: defect, Migrated from Trac, phing-tasks-phpunit
