### ISSUE TITLE
PhpCodeSnifferTask doesn't work with phpcs phar

### ISSUE THREAD

**Issue by dehrk** [phingofficial/phing#853] opened 2018-01-09 21:54 UTC
If only the phar is installed on the system, these lines throw an exception:
https://github.com/phingofficial/phing/blob/master/classes/phing/tasks/ext/PhpCodeSnifferTask.php#L413-L420

**Comment by mrook** [comment] 2018-02-13 15:18
Duplicate of #803.

**Closed by mrook** 2018-02-13 15:18 UTC
