### ISSUE TITLE
PHP 8 Support - Required parameter $project follows optional parameter $overwrite

### ISSUE THREAD

**Issue by renepardon** [phingofficial/phing#1604] opened 2021-05-18 06:56 UTC
Looks like there are still a few things to do for PHP 8 support. E.g.:

```
Deprecated: Required parameter $project follows optional parameter $overwrite in /builds/project/vendor/phing/phing/classes/phing/util/FileUtils.php on line 98
Call Stack:
    0.0001     431320   1. {main}() /builds/project/vendor/phing/phing/bin/phing:0
    0.0002     444736   2. require_once('/builds/project/vendor/phing/phing/bin/phing.php') /builds/project/vendor/phing/phing/bin/phing:14
    0.0299    8082944   3. require_once('/builds/project/vendor/phing/phing/classes/phing/Phing.php') /builds/project/vendor/phing/phing/bin/phing.php:27
    0.0300    8107488   4. require_once('/builds/project/vendor/phing/phing/classes/phing/Diagnostics.php') /builds/project/vendor/phing/phing/classes/phing/Phing.php:20
    0.0306    8304912   5. include_once('/builds/project/vendor/phing/phing/classes/phing/Project.php') /builds/project/vendor/phing/phing/classes/phing/Diagnostics.php:22
```

**Comment by mrook** [comment] 2021-05-18 06:58
Thanks for the report @renepardon. This is a duplicate of #1585.

**Closed by mrook** 2021-05-18 06:58 UTC

**Comment by renepardon** [comment] 2021-05-18 07:05
@mrook ahh ok, haven't seen it because it's also already closed but not yet merged in the latest available release.

**Comment by mrook** [comment] 2021-05-18 07:06
@renepardon we're not planning on doing any more fixes to 2.x, sorry!
